name: detranbet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'  # Defina aqui a versão mínima e máxima do SDK do Dart

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  lottie: ^3.1.2
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  asuka: ^2.2.1
  motion_toast: ^2.10.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
