name: Detranbet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Instala a versão especificada do Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.3'

      - name: Install dependencies
        run: flutter pub get

      # Verifica a formatação do código (opcional)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
